version: '3.8'
services:
  n8n:
    image: 'n8nio/n8n'
    restart: unless-stopped
    ports:
      - '5678:5678'
    volumes:
      - /opt/n8n/data:/home/node/.n8n
    environment:
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - N8N_SECURE_COOKIE=false
      # - N8N_BASIC_AUTH_ACTIVE=true
      # - N8N_BASIC_AUTH_USER=${N8N_USER}
      # - N8N_BASIC_AUTH_PASSWORD=${N8N_PASSWORD}
      - TZ=America/Manaus